package pojo;
// Generated 11-feb-2016 14:00:43 by Hibernate Tools 4.3.1



/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer id;
     private String calle;
     private Integer numero;
     private Integer piso;
     private Character letra;
     private Persona persona;

    public Direccion() {
    }
    
    public Direccion(String calle, Integer numero, Integer piso, Character letra) {
       this.calle = calle;
       this.numero = numero;
       this.piso = piso;
       this.letra = letra;
    }

    public Direccion(String calle, Integer numero, Integer piso, Character letra, Persona persona) {
       this.calle = calle;
       this.numero = numero;
       this.piso = piso;
       this.letra = letra;
       this.persona = persona;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public Character getLetra() {
        return this.letra;
    }
    
    public void setLetra(Character letra) {
        this.letra = letra;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Direccion(Integer id, String calle, Integer numero, Integer piso, Character letra) {
        this.id = id;
        this.calle = calle;
        this.numero = numero;
        this.piso = piso;
        this.letra = letra;
    }

}